# Code Coverage Workflow

name: Code Coverage

on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10.2"]
    env:
      OS: ubuntu-latest
      PYTHON: '3.10.2'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.10.2
    - name: Install dependencies
        run: pip install -r requirements.txt
    - name: Run tests and collect coverage
        run: |
          coverage run tests/test_parallel.py
          coverage xml
    - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
